"""empty message

Revision ID: 549d2c70381b
Revises: 7ac4c802c683
Create Date: 2019-05-21 17:35:15.748288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549d2c70381b'
down_revision = '7ac4c802c683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'name')
    # ### end Alembic commands ###
